# Generated by Django 5.0.6 on 2026-04-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='module',
            name='required_sessions',
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('T', 'Theory'), ('P', 'Practical')], default='T', max_length=1, verbose_name='Session Type'),
        ),
    ]
