# Generated by Django 5.0.6 on 2026-07-09 08:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_finance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcategory',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_categories', to='attendance.classlevel'),
        ),
        migrations.AddField(
            model_name='paymentcategory',
            name='installment_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum number of installments allowed for this category and level.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='paymentcategory',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_categories', to='attendance.semester'),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='installment_number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='paymentcategory',
            name='category_type',
            field=models.CharField(choices=[('school_fees', 'School Fees'), ('special_exam', 'Special Exam'), ('supp_exam', 'Supplementary Exam'), ('repeat_module', 'Repeat Module'), ('other', 'Other Payment')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentFinanceObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligation_type', models.CharField(choices=[('special_exam', 'Special Exam'), ('supp_exam', 'Supplementary Exam'), ('repeat_module', 'Repeat Module')], max_length=20)),
                ('amount_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='attendance.paymentcategory')),
                ('declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_obligations_declared', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_obligations', to='attendance.module')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_obligations', to='attendance.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_obligations', to='attendance.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='attendance.studentfinanceobligation'),
        ),
        migrations.CreateModel(
            name='StudentFinanceClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('cat1', 'CAT 1'), ('cat2', 'CAT 2'), ('end', 'End of Semester'), ('registration', 'Registration / Results')], max_length=20)),
                ('is_cleared', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_clearances_approved', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_clearances', to='attendance.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_clearances', to='attendance.student')),
            ],
            options={
                'ordering': ['student__name', 'period'],
                'unique_together': {('student', 'semester', 'period')},
            },
        ),
    ]
