# Generated by Django 5.0.6 on 2026-08-04 08:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_inventory_reference_data(apps, schema_editor):
    Location = apps.get_model('attendance', 'InventoryLocation')
    Category = apps.get_model('attendance', 'AssetCategory')
    locations = [
        'ICT & Examination Office', 'Finance & Administration Office', 'Staff Office',
        "Director's Office", "Secretary's Office", "Principal's Office", 'Library',
        'Level 4 Classroom', 'Level 5 Classroom', 'Level 6 Classroom',
        "Cleaners' Office", 'Security Guard Area', 'Other',
    ]
    categories = [
        'Computers and ICT Equipment', 'Printers and Office Equipment',
        'Furniture and Fittings', 'Teaching Equipment', 'Library Equipment',
        'Electrical Equipment', 'Cleaning Equipment', 'Security Equipment',
        'Buildings and Fixtures', 'Other',
    ]
    for name in locations:
        Location.objects.get_or_create(name=name)
    for name in categories:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_unique_attendance_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'asset categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstateOfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estate_officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=100, unique=True, verbose_name='Asset number/tag')),
                ('name', models.CharField(max_length=200, verbose_name='Asset name')),
                ('description', models.TextField()),
                ('responsible_office', models.CharField(max_length=200, verbose_name='Person/office responsible')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('unserviceable', 'Unserviceable')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='attendance.assetcategory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='attendance.inventorylocation')),
            ],
            options={
                'ordering': ['asset_tag'],
            },
        ),
        migrations.RunPython(seed_inventory_reference_data, migrations.RunPython.noop),
    ]
