# Generated by Django 4.2.30 on 2026-08-04 08:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0018_assetcategory_inventorylocation_assetimport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('inspector_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='attendance.inventorylocation')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_inspections_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_responsible_office', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('transferred_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='attendance.asset')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='attendance.inventorylocation')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_recorded', to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='attendance.inventorylocation')),
            ],
            options={
                'ordering': ['-transferred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='reported', max_length=20)),
                ('reported_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='attendance.asset')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_maintenance_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('method', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('disposed', 'Disposed')], default='proposed', max_length=20)),
                ('proposed_date', models.DateField()),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disposal', to='attendance.asset')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_disposals_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-proposed_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryInspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('found', 'Found'), ('missing', 'Missing'), ('damaged', 'Damaged'), ('relocated', 'Relocated')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_items', to='attendance.asset')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='attendance.inventoryinspection')),
            ],
            options={
                'ordering': ['asset__asset_tag'],
                'unique_together': {('inspection', 'asset')},
            },
        ),
    ]
