# Generated by Django 4.2.30 on 2026-08-04 09:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_inventoryinspection_alter_asset_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmaintenance',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='resulting_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='split_from_transfers', to='attendance.asset'),
        ),
    ]
