# Generated by Django 5.0.6 on 2026-08-28 10:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('family', models.CharField(choices=[('fee', 'School Fees'), ('direct_cost', 'Direct Costs'), ('other', 'Other Payments')], default='fee', max_length=20)),
                ('applies', models.CharField(choices=[('automatic', 'Every student in the level'), ('optional', 'Only students assigned it (hostel, field trips)'), ('on_request', 'Only when the college declares it (supplementary, repeat)')], default='automatic', max_length=20)),
                ('blocks_registration', models.BooleanField(default=False, verbose_name='Blocks registration')),
                ('blocks_cat1', models.BooleanField(default=False, verbose_name='Blocks CAT 1')),
                ('blocks_cat2', models.BooleanField(default=False, verbose_name='Blocks CAT 2')),
                ('blocks_final', models.BooleanField(default=False, verbose_name='Blocks end-of-semester exam')),
                ('blocks_results', models.BooleanField(default=False, verbose_name='Blocks results release')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['family', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nactvet_reg_no', models.CharField(max_length=50, unique=True, verbose_name='NACTVET Reg. No.')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('billing_period', models.CharField(choices=[('academic_year', 'Once per academic year'), ('semester', 'Once per semester')], default='academic_year', max_length=20)),
                ('installments', models.PositiveSmallIntegerField(default=1, help_text='Level 4 fees are paid over 5; Levels 5 and 6 over 4.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='attendance.academicyear')),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='attendance.chargetype')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='attendance.classlevel')),
            ],
            options={
                'ordering': ['academic_year__name', 'class_level__order', 'charge_type__family', 'charge_type__name'],
            },
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_date', models.DateField()),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_schedule', to='attendance.feestructure')),
            ],
            options={
                'ordering': ['fee_structure', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('issued_on', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('student', 'Generated by the student'), ('office', 'Raised at the office')], default='student', max_length=10)),
                ('cancelled', models.BooleanField(default=False)),
                ('cancelled_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='attendance.academicyear')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='attendance.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(verbose_name='Date on the slip')),
                ('channel', models.CharField(choices=[('crdb', 'CRDB bank deposit'), ('mobile', 'Mobile money'), ('cash', 'Cash at the office')], default='crdb', max_length=20)),
                ('bank_reference', models.CharField(blank=True, help_text="The bank's own transaction number from the slip.", max_length=100)),
                ('efd_receipt_no', models.CharField(blank=True, help_text='From the EFD machine. Links this record to the fiscal receipt.', max_length=100, verbose_name='EFD receipt no.')),
                ('payer_name', models.CharField(blank=True, max_length=200)),
                ('payer_relation', models.CharField(choices=[('self', 'The student'), ('parent', 'Parent'), ('guardian', 'Guardian'), ('sponsor', 'Sponsor'), ('employer', 'Employer')], default='self', max_length=20)),
                ('proof', models.FileField(blank=True, null=True, upload_to='payment-proof/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('note', models.CharField(blank=True, max_length=300)),
                ('reversal_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='attendance.invoice')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='attendance.payment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_payments', to='attendance.studentprofile')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_date', models.DateField()),
                ('source', models.CharField(choices=[('structure', 'Generated from the fee structure'), ('on_request', 'Raised on request'), ('carry_forward', 'Brought forward from a previous year')], default='structure', max_length=20)),
                ('waived_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('waived_reason', models.CharField(blank=True, max_length=300)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='attendance.academicyear')),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='attendance.chargetype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_created', to=settings.AUTH_USER_MODEL)),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='attendance.feestructure')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='attendance.semester')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_waived', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='attendance.studentprofile')),
            ],
            options={
                'ordering': ['due_date', 'charge_type__family', 'charge_type__name', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='attendance.payment')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='attendance.studentcharge')),
            ],
            options={
                'ordering': ['charge__due_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='attendance.invoice')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='attendance.studentcharge')),
            ],
            options={
                'ordering': ['charge__due_date'],
            },
        ),
        migrations.CreateModel(
            name='FinanceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('registration', 'Registration'), ('cat1', 'CAT 1'), ('cat2', 'CAT 2'), ('final', 'End-of-semester exam'), ('results', 'Results release')], max_length=20)),
                ('status', models.CharField(choices=[('cleared', 'Cleared'), ('blocked', 'Blocked')], default='cleared', max_length=10)),
                ('reason', models.CharField(max_length=300)),
                ('expires_on', models.DateField(blank=True, help_text='After this date the override lapses and the ledger decides again.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_overrides', to='attendance.academicyear')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_overrides_approved', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_overrides', to='attendance.semester')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_overrides', to='attendance.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('entity', models.CharField(max_length=60)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.CharField(max_length=300)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='attendance.studentprofile')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='attendance.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('charge_type', 'class_level', 'academic_year'), name='unique_fee_structure_cell'),
        ),
        migrations.AddConstraint(
            model_name='feeinstallment',
            constraint=models.UniqueConstraint(fields=('fee_structure', 'number'), name='unique_fee_installment_number'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'charge'), name='unique_payment_allocation'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'charge'), name='unique_invoice_line_charge'),
        ),
        migrations.AddIndex(
            model_name='studentcharge',
            index=models.Index(fields=['profile', 'academic_year'], name='attendance__profile_6b93da_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcharge',
            index=models.Index(fields=['due_date'], name='attendance__due_dat_9674d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentcharge',
            constraint=models.UniqueConstraint(fields=('profile', 'charge_type', 'academic_year', 'semester', 'installment_number'), name='unique_student_charge_installment'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['profile', '-payment_date'], name='attendance__profile_4851e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('amount__gt', 0), ('reverses__isnull', True)), models.Q(('amount__lt', 0), ('reverses__isnull', False)), _connector='OR'), name='payment_sign_matches_reversal'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['profile', '-created_at'], name='attendance__profile_945572_idx'),
        ),
        migrations.AddIndex(
            model_name='financeoverride',
            index=models.Index(fields=['profile', 'academic_year', 'period'], name='attendance__profile_193efb_idx'),
        ),
        migrations.AddIndex(
            model_name='financeauditlog',
            index=models.Index(fields=['-at'], name='attendance__at_ada4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='financeauditlog',
            index=models.Index(fields=['entity', 'entity_id'], name='attendance__entity_46a88a_idx'),
        ),
    ]
