# Generated by Django 5.0.6 on 2026-08-28 12:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_backfill_student_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='CRDB', max_length=120)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=64, unique=True)),
                ('purpose', models.CharField(help_text='What this account collects, e.g. "Tuition fee" or "Other charges & accommodation".', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['purpose', 'account_number'],
            },
        ),
        migrations.CreateModel(
            name='CollegeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Blue Pharma College of Health', max_length=200)),
                ('short_name', models.CharField(default='BPHACOH', max_length=60)),
                ('po_box', models.CharField(blank=True, max_length=60)),
                ('town', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='Tanzania', max_length=80)),
                ('phone', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=160)),
                ('logo', models.FileField(blank=True, null=True, upload_to='college/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])])),
                ('invoice_terms', models.TextField(blank=True, help_text='Shown under Terms & Conditions on every invoice, one rule per line.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'college profile',
            },
        ),
        migrations.AddField(
            model_name='chargetype',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once — never repeated'), ('each_year', 'Each year'), ('each_semester', 'Each semester')], default='each_year', max_length=20),
        ),
        migrations.AddField(
            model_name='chargetype',
            name='invoice_group',
            field=models.CharField(blank=True, help_text='Charges sharing a group are invoiced together, e.g. "Tuition Fee", "Direct Costs", "Accommodation". Defaults to the group name.', max_length=80),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_group',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='billing_period',
            field=models.CharField(choices=[('academic_year', 'Once per academic year'), ('semester', 'Once per semester'), ('once', 'Once for the whole programme')], default='academic_year', max_length=20),
        ),
        migrations.AddField(
            model_name='chargetype',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge_types', to='attendance.bankaccount'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='attendance.bankaccount'),
        ),
    ]
