# Generated by Django 5.0.6 on 2026-08-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_one_invoice_per_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargetype',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='Item code'),
        ),
    ]
