# Generated by Django 5.0.6 on 2026-08-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_charge_type_item_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargetype',
            options={'ordering': ['family', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='chargetype',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Position in the published fee table. Items with the same order fall back to alphabetical.', verbose_name='Row order'),
        ),
    ]
