# Generated by Django 5.0.6 on 2026-08-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_evaluation_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='audience',
            field=models.CharField(choices=[('student', 'Students — filled in on the student portal'), ('staff', 'Staff — filled in by a tutor, mentor or officer')], default='student', max_length=20),
        ),
    ]
