# Generated by Django 5.0.6 on 2026-09-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_form_response_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Students see this form on sign-in and cannot use the portal until they have answered it. Student forms only.', verbose_name='Every student must fill this in'),
        ),
    ]
