# Generated by Django 5.0.6 on 2026-09-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0035_form_is_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='levels',
            field=models.ManyToManyField(blank=True, help_text='Which levels are asked to fill this in. Leave empty for all of them.', related_name='forms', to='attendance.classlevel', verbose_name='NTA levels'),
        ),
    ]
