# Generated by Django 5.0.6 on 2026-09-02 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0036_form_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='kind',
            field=models.CharField(choices=[('evaluation', 'Evaluation — feedback the college tallies and reports on'), ('request', 'Service request — one student asking for something, owed an answer')], default='evaluation', max_length=20),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='decision_note',
            field=models.TextField(blank=True, help_text='Shown to the student with the decision — where to collect it, or why it was declined.'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'With the college'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
