# Generated by Django 5.0.6 on 2026-09-02 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0037_service_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='print_note',
            field=models.TextField(blank=True, help_text='Notes printed at the foot of the approved document, one per line.'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='for_office',
            field=models.BooleanField(default=False, help_text='Hidden in the portal. Printed as blank lines on the approved document for a health facility, a Head of Department or the Dean of Students.', verbose_name='Filled in on paper by an office, not by the student'),
        ),
        migrations.CreateModel(
            name='SecretaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secretary_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
