# Generated by Django 5.0.6 on 2026-09-07 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0042_request_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='forward_note',
            field=models.CharField(blank=True, help_text='What the secretary wants the Principal or HoD to know. Not shown to the student.', max_length=300),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='forwarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_forwards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'With the secretary'), ('forwarded', 'With the Principal / Head of Department'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('request.submitted', 'A student asked for something'), ('request.forwarded', 'A request needs a decision'), ('request.decided', 'A request was answered'), ('request.document', 'A document was sent'), ('form.published', 'A form was opened')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('link', models.CharField(blank=True, max_length=120)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.studentprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at', '-created_at'], name='attendance__user_id_dc73c4_idx'), models.Index(fields=['profile', 'read_at', '-created_at'], name='attendance__profile_72fb68_idx')],
            },
        ),
    ]
