# Generated by Django 5.0.6 on 2026-09-16 16:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0043_request_workflow_and_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionOfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='First or second next of kin.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('relationship', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('relative', 'Other relative'), ('other', 'Other')], max_length=20)),
            ],
            options={
                'ordering': ['profile', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecordsOfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('new', 'New to the college'), ('continuing', 'Continuing'), ('repeating', 'Repeating failed modules'), ('readmission', 'Readmitted'), ('imported', 'Recorded from enrollments made before registrations were kept')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-semester__academic_year__name', '-semester__number', 'profile__name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='feestructure',
            name='unique_fee_structure_cell',
        ),
        migrations.AddField(
            model_name='chargetype',
            name='charged_again_on_readmission',
            field=models.BooleanField(default=True, help_text='For a charge billed once, bill it again when a discontinued student is readmitted.'),
        ),
        migrations.AddField(
            model_name='chargetype',
            name='declaration',
            field=models.CharField(blank=True, choices=[('special_exam', 'Special exam'), ('supp_exam', 'Supplementary exam'), ('repeat_module', 'Repeat module')], help_text='Raised per module when the examination office declares a student for this.', max_length=20),
        ),
        migrations.AddField(
            model_name='studentcharge',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='attendance.module'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='College ID No.'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='chargetype',
            constraint=models.UniqueConstraint(condition=models.Q(('declaration', ''), _negated=True), fields=('declaration',), name='one_charge_type_per_declaration'),
        ),
        migrations.AddField(
            model_name='admissionofficerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_officer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to=settings.AUTH_USER_MODEL, verbose_name='Head of department'),
        ),
        migrations.AddField(
            model_name='department',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='attendance.studentprofile'),
        ),
        migrations.AddField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='attendance.department'),
        ),
        migrations.AddField(
            model_name='programme',
            name='levels',
            field=models.ManyToManyField(blank=True, help_text='The NTA levels this programme is taught at.', related_name='programmes', to='attendance.classlevel'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='Leave blank for an amount every programme pays.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='attendance.programme'),
        ),
        migrations.AddField(
            model_name='module',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='attendance.programme'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(condition=models.Q(('programme__isnull', True)), fields=('charge_type', 'class_level', 'academic_year'), name='unique_fee_structure_cell'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(condition=models.Q(('programme__isnull', False)), fields=('charge_type', 'programme', 'class_level', 'academic_year'), name='unique_programme_fee_structure_cell'),
        ),
        migrations.AddField(
            model_name='recordsofficerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='records_officer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='attendance.classlevel'),
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='attendance.studentprofile'),
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='attendance.programme'),
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='attendance.semester'),
        ),
        migrations.AddConstraint(
            model_name='nextofkin',
            constraint=models.UniqueConstraint(fields=('profile', 'position'), name='one_next_of_kin_per_position'),
        ),
        migrations.AddConstraint(
            model_name='nextofkin',
            constraint=models.CheckConstraint(check=models.Q(('position__in', [1, 2])), name='next_of_kin_position_one_or_two'),
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_programme_name_per_department'),
        ),
        migrations.AddConstraint(
            model_name='semesterregistration',
            constraint=models.UniqueConstraint(fields=('profile', 'semester'), name='one_registration_per_semester'),
        ),
    ]
