# Generated by Django 5.0.6 on 2026-09-17 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0044_departments_programmes_registrations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterregistration',
            name='cancelled_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='status',
            field=models.CharField(choices=[('active', 'Studying'), ('cancelled', 'Cancelled')], default='active', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='attempt',
            field=models.CharField(choices=[('normal', 'First sitting'), ('repeat', 'Repeat sitting')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='repeat_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeat_attempts', to='attendance.student'),
        ),
        migrations.CreateModel(
            name='OutstandingRepeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=50)),
                ('module_name', models.CharField(blank=True, max_length=200)),
                ('semester_number', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')])),
                ('status', models.CharField(choices=[('open', 'Still to be passed'), ('passed', 'Passed on a repeat sitting'), ('cancelled', 'Cancelled by the office')], default='open', max_length=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_enrollment', models.ForeignKey(blank=True, help_text='The latest repeat sitting of this module.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeats_attempted', to='attendance.student')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outstanding_repeats', to='attendance.classlevel')),
                ('origin_enrollment', models.ForeignKey(blank=True, help_text='The failed enrollment, kept as the evidence. Never rewritten.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeats_raised', to='attendance.student')),
                ('origin_semester', models.ForeignKey(help_text='The semester the module was failed in — the year the student is held to.', on_delete=django.db.models.deletion.PROTECT, related_name='repeats_raised', to='attendance.semester')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outstanding_repeats', to='attendance.studentprofile')),
            ],
            options={
                'ordering': ['profile__name', 'origin_semester__academic_year__name', 'module_code'],
            },
        ),
        migrations.CreateModel(
            name='SemesterReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('proposed', models.CharField(choices=[('clear', 'Passed everything'), ('repeat', 'Repeats the failed module(s)'), ('discontinued', 'Discontinued — GPA below 2.0'), ('completed', 'Finished level 6'), ('pending', 'Waiting for results'), ('provisional', 'Continues while supplementary results are awaited'), ('postponed', 'Postponed')], max_length=20)),
                ('proposed_reason', models.CharField(blank=True, max_length=300)),
                ('confirmed', models.CharField(blank=True, choices=[('clear', 'Passed everything'), ('repeat', 'Repeats the failed module(s)'), ('discontinued', 'Discontinued — GPA below 2.0'), ('completed', 'Finished level 6'), ('pending', 'Waiting for results'), ('provisional', 'Continues while supplementary results are awaited'), ('postponed', 'Postponed')], default='', max_length=20)),
                ('confirmed_reason', models.CharField(blank=True, max_length=300)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='attendance.classlevel')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_confirmed', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_reviews', to='attendance.studentprofile')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='attendance.programme')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='attendance.semester')),
            ],
            options={
                'ordering': ['-semester__academic_year__name', '-semester__number', 'profile__name'],
            },
        ),
        migrations.CreateModel(
            name='StandingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standing_changes_made', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_changes', to='attendance.studentprofile')),
                ('semester', models.ForeignKey(blank=True, help_text='The semester whose results or decision caused the move.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standing_changes', to='attendance.semester')),
            ],
            options={
                'ordering': ['-created_at', 'profile__name'],
            },
        ),
        migrations.CreateModel(
            name='StudentStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Studying'), ('repeating', 'Repeating failed modules'), ('postponed', 'Postponed'), ('discontinued', 'Discontinued — may return on readmission'), ('completed', 'Finished studies, awaiting clearance'), ('archived', 'Cleared and archived')], default='active', max_length=20)),
                ('return_semester_number', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2')], help_text='The semester they return to — a student who failed semester 2 comes back to semester 2, not to the start of the year.', null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(blank=True, help_text='The level the student is at now, or was at when they left.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standings', to='attendance.classlevel')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standing', to='attendance.studentprofile')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standings', to='attendance.programme')),
                ('return_year', models.ForeignKey(blank=True, help_text='The year a postponed or discontinued student is expected back.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returning_students', to='attendance.academicyear')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['profile__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='outstandingrepeat',
            constraint=models.UniqueConstraint(fields=('profile', 'module_code', 'origin_semester'), name='one_repeat_per_module_per_semester'),
        ),
        migrations.AddConstraint(
            model_name='semesterreview',
            constraint=models.UniqueConstraint(fields=('profile', 'semester'), name='one_review_per_semester'),
        ),
    ]
