# Generated by Django 5.0.6 on 2026-09-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0045_progression_standings_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='withdrawn_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
