# Generated by Django 5.0.6 on 2026-09-21 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0046_withdrawn_enrollments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('frequency', models.CharField(choices=[('each_semester', 'Checked every semester'), ('each_year', 'Checked once a year'), ('once', 'Checked once, when they join')], default='each_semester', max_length=20)),
                ('mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applies_to_levels', models.ManyToManyField(blank=True, help_text='Leave empty for every level.', related_name='requirements', to='attendance.classlevel')),
                ('charge_type', models.ForeignKey(blank=True, help_text='What the college charges when the student does not have it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='attendance.chargetype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opens_on', models.DateField()),
                ('closes_on', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to close admissions immediately, whatever the dates say.')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_windows_opened', to=settings.AUTH_USER_MODEL)),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='admission_window', to='attendance.semester')),
            ],
            options={
                'ordering': ['-semester__academic_year__name', '-semester__number'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('new', 'First year'), ('continuing', 'Continuing student'), ('readmission', 'Readmission')], max_length=20)),
                ('state', models.CharField(choices=[('information', "Collecting the student's information"), ('finance', 'With finance'), ('records', 'With records'), ('admission', 'With the admission officer'), ('admitted', 'Admitted'), ('rejected', 'Refused'), ('cancelled', 'Withdrawn')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('decided_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='attendance.classlevel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_opened', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='attendance.studentprofile')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='attendance.programme')),
                ('registration', models.OneToOneField(blank=True, help_text='Created when the admission officer admits them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='attendance.semesterregistration')),
                ('returning_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readmissions', to='attendance.semester')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='attendance.semester')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('information', "Collecting the student's information"), ('finance', 'With finance'), ('records', 'With records'), ('admission', 'With the admission officer'), ('admitted', 'Admitted'), ('rejected', 'Refused'), ('cancelled', 'Withdrawn')], max_length=20)),
                ('done_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='attendance.application')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['done_at'],
            },
        ),
        migrations.CreateModel(
            name='CollegeIdFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(default='{COLLEGE}/{PROG}/{YEAR}/{SEQ}', help_text='Where each piece goes. {COLLEGE} {PROG} {YEAR} {YY} {SEQ}', max_length=120)),
                ('college_code', models.CharField(default='BPH', max_length=20)),
                ('starts_at', models.PositiveIntegerField(default=1, help_text='The first number of the year.')),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('sequence_width', models.PositiveSmallIntegerField(default=3, help_text='How many digits the running number is padded to.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_id_format', to='attendance.academicyear')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_id_formats_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_year__name'],
            },
        ),
        migrations.CreateModel(
            name='RequirementCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('has_it', 'Has it'), ('missing', 'Missing — charged'), ('waived', 'Waived by the college')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_checks', to='attendance.application')),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_checks', to='attendance.studentcharge')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_checks', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='attendance.admissionrequirement')),
            ],
            options={
                'ordering': ['requirement__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('profile', 'semester'), name='one_application_per_semester'),
        ),
        migrations.AddConstraint(
            model_name='requirementcheck',
            constraint=models.UniqueConstraint(fields=('application', 'requirement'), name='one_check_per_requirement_per_application'),
        ),
    ]
