# Generated by Django 5.0.6 on 2026-09-21 10:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0047_admission_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('intake', 'Intake — the admission office takes them on'), ('information', 'Records — details and documents'), ('finance', 'With finance'), ('records', 'With records'), ('admission', 'With the admission officer'), ('admitted', 'Admitted'), ('rejected', 'Refused'), ('cancelled', 'Withdrawn')], max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationstep',
            name='step',
            field=models.CharField(choices=[('intake', 'Intake — the admission office takes them on'), ('information', 'Records — details and documents'), ('finance', 'With finance'), ('records', 'With records'), ('admission', 'With the admission officer'), ('admitted', 'Admitted'), ('rejected', 'Refused'), ('cancelled', 'Withdrawn')], max_length=20),
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('certificate', 'Certificate'), ('result_slip', 'Result slip'), ('birth_certificate', 'Birth certificate'), ('identity', 'Identification'), ('medical', 'Medical form'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(help_text='A scan or a photograph — PDF, JPG or PNG.', upload_to='student_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('uploaded_by_student', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='attendance.studentprofile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_documents_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
