# Generated by Django 5.0.6 on 2026-09-21 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0048_student_documents_and_intake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='portal_pin_set_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='PasswordStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('must_change', models.BooleanField(default=False)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passwords_reset', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'password statuses',
                'ordering': ['user__username'],
            },
        ),
    ]
