# Generated by Django 5.0.6 on 2026-09-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0049_password_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='kind',
            field=models.CharField(choices=[('o_level', 'O-level certificate (CSEE)'), ('a_level', 'A-level certificate (ACSEE)'), ('certificate', 'Other certificate'), ('result_slip', 'Result slip'), ('birth_certificate', 'Birth certificate'), ('identity', 'Identification'), ('medical', 'Medical form'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
