# Generated by Django 5.0.6 on 2026-09-23 17:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def mark_accommodation_as_hostel(apps, schema_editor):
    """The fee catalogue's Accommodation row (row 15 of the admission form) is
    the hostel fee."""
    ChargeType = apps.get_model('attendance', 'ChargeType')
    ChargeType.objects.filter(name='Accommodation').update(is_hostel=True)


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0051_item_checks_per_semester_and_holds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chargetype',
            name='is_hostel',
            field=models.BooleanField(default=False, help_text='Charged to students living in the hostel, and only to them.', verbose_name='Hostel fee'),
        ),
        migrations.CreateModel(
            name='HostelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('approved', 'Granted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostel_applications', to='attendance.academicyear')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_applications_decided', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_applications', to='attendance.studentprofile')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostel_applications', to='attendance.semester')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(choices=[('new', 'New students (level 4, and new entrants at levels 5 and 6)'), ('continuing', 'Continuing students')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='attendance.academicyear')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_schedules_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['academic_year__name', 'entry'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('due_date', models.DateField()),
                ('semester_number', models.PositiveSmallIntegerField(default=1, help_text='The semester this instalment belongs to (muhula wa kwanza / wa pili).', validators=[django.core.validators.MinValueValidator(1)])),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='attendance.paymentschedule')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStepAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_step_amounts', to='attendance.chargetype')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='attendance.paymentstep')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence', models.CharField(choices=[('day', 'Day'), ('hostel', 'Hostel')], max_length=10)),
                ('from_semester_number', models.PositiveSmallIntegerField(default=1)),
                ('source', models.CharField(choices=[('finance_desk', 'Stated at the finance desk'), ('carried', 'Carried from last year'), ('application', 'Hostel application granted')], default='finance_desk', max_length=20)),
                ('set_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residences', to='attendance.academicyear')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='attendance.studentprofile')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residences_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_year__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentschedule',
            constraint=models.UniqueConstraint(fields=('academic_year', 'entry'), name='one_payment_schedule_per_entry'),
        ),
        migrations.AddConstraint(
            model_name='paymentstep',
            constraint=models.UniqueConstraint(fields=('schedule', 'number'), name='one_payment_step_number'),
        ),
        migrations.AddConstraint(
            model_name='paymentstepamount',
            constraint=models.UniqueConstraint(fields=('step', 'charge_type'), name='one_amount_per_step_and_charge'),
        ),
        migrations.AddConstraint(
            model_name='studentresidence',
            constraint=models.UniqueConstraint(fields=('profile', 'academic_year'), name='one_residence_per_year'),
        ),
        migrations.RunPython(mark_accommodation_as_hostel, migrations.RunPython.noop),
    ]
