# Generated by Django 5.0.6 on 2026-09-23 19:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0052_payment_schedules_and_hostel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('balance_at_clearance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('finance_note', models.CharField(blank=True, max_length=300)),
                ('declared_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Postponement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('by_student', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Waiting for the Principal'), ('approved', 'Approved'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=300)),
                ('return_semester_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fees_reversed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payment_sign_matches_reversal',
        ),
        migrations.AlterField(
            model_name='payment',
            name='channel',
            field=models.CharField(choices=[('crdb', 'CRDB bank deposit'), ('mobile', 'Mobile money'), ('cash', 'Cash at the office'), ('credit', 'Credit carried forward')], default='crdb', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('amount__gt', 0), ('reverses__isnull', True)), models.Q(('amount__lt', 0), ('reverses__isnull', False)), models.Q(('amount', 0), ('channel', 'credit'), ('reverses__isnull', True)), _connector='OR'), name='payment_sign_matches_reversal'),
        ),
        migrations.AddField(
            model_name='completionclearance',
            name='declared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions_declared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completionclearance',
            name='finance_cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions_finance_cleared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completionclearance',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='attendance.studentprofile'),
        ),
        migrations.AddField(
            model_name='postponement',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postponements_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postponement',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postponements_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postponement',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postponements', to='attendance.studentprofile'),
        ),
        migrations.AddField(
            model_name='postponement',
            name='return_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postponed_returns', to='attendance.academicyear'),
        ),
        migrations.AddField(
            model_name='postponement',
            name='semester',
            field=models.ForeignKey(help_text='The semester they stop in.', on_delete=django.db.models.deletion.PROTECT, related_name='postponements', to='attendance.semester'),
        ),
    ]
